apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    {{- include "home-assistant.labels" . | nindent 4 }}
  name: {{ .Values.persistence.pvcName | default include "home-assistant.fullname" . }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
