apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    {{- include "home-assistant.labels" . | nindent 4 }}
  name: {{ include "home-assistant.pvcName" . }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
